// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://localhost:1337/',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'pt-BR'],
  server: 'http://localhost:1337/'
};
